apiVersion: v1
kind: Pod
metadata:
  name: env-single-secret
spec:
  containers:
    - name: envars-test-container
      image: nginx
      env:
        - name: MY_ENV_VAR
          value: "1234"
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: test-secret
              key: password