version: "3.7"

services:
  mysql:
    image: mysql:5.7
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${SECRET}
      MYSQL_DATABASE: videos

  chat-app:
    build: ./
    ports:
      - 8082:8080
    environment:
      DB_ROOT_PASS: ${SECRET}
      DB_NAME: videos
    depends_on:
      - mysql
volumes:
  mysql-data: